run-name: Build Wazuh Puppet module ${{ inputs.BRANCH_NAME }}
name: Puppet Module Builder

on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME:
        type: string
        description: "Branch or tag name"
        required: true
        default: "v4.10.0"
      UPLOAD_S3:
        type: boolean
        description: "Upload Puppet module to S3"
        required: true
        default: false
      S3_REPOSITORY:
        type: choice
        description: "S3 Repository"
        required: true
        options:
          - staging
          - pre-release

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build_module:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.BRANCH_NAME }}

      - name: View parameters
        run: echo "${{ toJson(inputs) }}"

      - name: Create environment variables for workflow
        run: |
            WAZUH_TAG=$(curl --silent https://api.github.com/repos/wazuh/wazuh/git/refs/tags | grep '["]ref["]:' | sed -E 's/.*\"([^\"]+)\".*/\1/'  | cut -c 11- | grep ^${{ inputs.BRANCH_NAME }}$)
            PUPPET_MODULE_NAME=$(jq .name ${{ github.workspace }}/metadata.json | sed -e 's|["'\'']||g')
            PUPPET_MODULE_VERSION=$(jq .version ${{ github.workspace }}/metadata.json | sed -e 's|["'\'']||g')
            echo "WAZUH_TAG=$WAZUH_TAG" >> "$GITHUB_ENV"
            echo "PUPPET_MODULE_NAME=$PUPPET_MODULE_NAME" >> "$GITHUB_ENV"
            echo "PUPPET_MODULE_VERSION=$PUPPET_MODULE_VERSION" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
            curl -O https://apt.puppet.com/puppet-tools-release-noble.deb
            sudo dpkg -i puppet-tools-release-noble.deb
            sudo apt-get update
            sudo apt-get install pdk
            pdk set config user.analytics.disabled false --type boolean --force

      - name: Build Wazuh Puppet module
        run: |
            mkdir -p ${{ github.workspace }}/output
            pdk build --force --target-dir=${{ github.workspace }}/output/

      - name: Create Puppet module artifact
        uses: actions/upload-artifact@v4
        with:
          name: Puppet module artifact
          path: ${{ github.workspace }}/output/${{ env.PUPPET_MODULE_NAME }}-${{ env.PUPPET_MODULE_VERSION }}.tar.gz
          retention-days: 1

      - name: Configure aws credentials
        if: ${{ env.WAZUH_TAG != '' && inputs.UPLOAD_S3 == true }}
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_PUPPET_ROLE }}
          aws-region: "${{ secrets.AWS_REGION }}"

      - name: Upload Puppet module to S3
        if: ${{ env.WAZUH_TAG != '' && inputs.UPLOAD_S3 == true }}
        run: aws s3 cp ${{ github.workspace }}/output/${{ env.PUPPET_MODULE_NAME }}-${{ env.PUPPET_MODULE_VERSION }}.tar.gz s3://${{ secrets.AWS_S3_BUCKET }}/${{ inputs.S3_REPOSITORY }}/puppet-module/

